
services:
    - docker

language: python
python: '3.6'

env:
    - MAKE_TARGET=test
    - MAKE_TARGET=itest_xenial
    - MAKE_TARGET=itest_bionic
    - MAKE_TARGET=itest_stretch
    - MAKE_TARGET=itest_buster

before_install:
    - pip install tox
    - sudo apt-get install -y --no-install-recommends zsh
    # write-safety tests fail otherwise
    - umask 022


script:
    - make $MAKE_TARGET
