#!/bin/bash -eux
# This script gets run inside the itest Docker containers.
set -o pipefail

# We need to set standard /tmp permissions since it's a Docker volume.
chmod 1777 /tmp

if grep -qE '\<lucid\>' /etc/apt/sources.list; then
    # lucid was archived, breaking the base image
    # https://github.com/docker-library/official-images/issues/1902
    sed -i 's@archive\.ubuntu\.com@archive.kernel.org/ubuntu-archive@g' /etc/apt/sources.list

    apt-get update
    apt-get install -y --no-install-recommends python-software-properties

    # for python2.7 backport
    add-apt-repository ppa:fkrull/deadsnakes
    # for zsh 5 backport (lucid's zsh segfaults)
    add-apt-repository ppa:blueyed/ppa
else
    # The default mirrors are too flaky to run reliably in CI.
    sed -E \
        '/security\.debian/! s@http://[^/]+/@http://mirrors.kernel.org/@' \
        -i /etc/apt/sources.list
fi

apt-get update
apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    ca-certificates \
    curl \
    gdebi-core \
    python3-dev \
    zsh

curl https://bootstrap.pypa.io/get-pip.py | python3
gdebi -n /mnt/dist/*.deb
pip install -r /mnt/requirements-dev.txt
pip install /mnt

# pytest can't deal with a read-only filesystem
cp -r /mnt /tmp/test
py.test -vv /tmp/test
