#!/bin/bash -eux
# This script gets run inside the itest Docker containers.
set -o pipefail

# We need to set standard /tmp permissions since it's a Docker volume.
chmod 1777 /tmp

# The default mirrors are too flaky to run reliably in CI.
sed -E \
    '/security\.debian/! s@http://[^/]+/@http://mirrors.kernel.org/@' \
    -i /etc/apt/sources.list

apt-get update
apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    ca-certificates \
    curl \
    gdebi-core \
    python3-dev \
    zsh

if grep -qE '\<lucid\>' /etc/apt/sources.list; then
    apt-get install -y --no-install-recommends python3.4-dev
    ln -s /usr/bin/python3.4 /usr/local/bin/python3
fi

curl https://bootstrap.pypa.io/get-pip.py | python3
gdebi -n /mnt/dist/*.deb
pip install -r /mnt/requirements-dev.txt
pip install /mnt

# pytest can't deal with a read-only filesystem
cp -r /mnt /tmp/test
py.test -vv /tmp/test
