---
name: build
on: [push, pull_request]
jobs:
  make:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        make_target:
          - test
          - itest_focal
          - itest_jammy
          - itest_noble
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install tox
      - run: sudo apt-get install -y --no-install-recommends zsh
      - run: make ${{ matrix.make_target }}
